import type { SchemaCatalogPair } from "../internal/catalogBuilder";

import {
  AuthorizeRequestSchema,
  AuthorizeResponseSchema,
  BootNotificationRequestSchema,
  BootNotificationResponseSchema,
  CancelReservationRequestSchema,
  CancelReservationResponseSchema,
  ChangeAvailabilityRequestSchema,
  ChangeAvailabilityResponseSchema,
  ChangeConfigurationRequestSchema,
  ChangeConfigurationResponseSchema,
  ClearCacheRequestSchema,
  ClearCacheResponseSchema,
  ClearChargingProfileRequestSchema,
  ClearChargingProfileResponseSchema,
  DataTransferRequestSchema,
  DataTransferResponseSchema,
  DiagnosticsStatusNotificationRequestSchema,
  DiagnosticsStatusNotificationResponseSchema,
  FirmwareStatusNotificationRequestSchema,
  FirmwareStatusNotificationResponseSchema,
  GetCompositeScheduleRequestSchema,
  GetCompositeScheduleResponseSchema,
  GetConfigurationRequestSchema,
  GetConfigurationResponseSchema,
  GetDiagnosticsRequestSchema,
  GetDiagnosticsResponseSchema,
  GetLocalListVersionRequestSchema,
  GetLocalListVersionResponseSchema,
  HeartbeatRequestSchema,
  HeartbeatResponseSchema,
  MeterValuesRequestSchema,
  MeterValuesResponseSchema,
  RemoteStartTransactionRequestSchema,
  RemoteStartTransactionResponseSchema,
  RemoteStopTransactionRequestSchema,
  RemoteStopTransactionResponseSchema,
  ReserveNowRequestSchema,
  ReserveNowResponseSchema,
  ResetRequestSchema,
  ResetResponseSchema,
  SendLocalListRequestSchema,
  SendLocalListResponseSchema,
  SetChargingProfileRequestSchema,
  SetChargingProfileResponseSchema,
  StartTransactionRequestSchema,
  StartTransactionResponseSchema,
  StatusNotificationRequestSchema,
  StatusNotificationResponseSchema,
  StopTransactionRequestSchema,
  StopTransactionResponseSchema,
  TriggerMessageRequestSchema,
  TriggerMessageResponseSchema,
  UnlockConnectorRequestSchema,
  UnlockConnectorResponseSchema,
  UpdateFirmwareRequestSchema,
  UpdateFirmwareResponseSchema,
} from "./schemas";

export const ocpp16SchemaPairs = [
  ["Authorize", AuthorizeRequestSchema, AuthorizeResponseSchema],
  ["BootNotification", BootNotificationRequestSchema, BootNotificationResponseSchema],
  ["CancelReservation", CancelReservationRequestSchema, CancelReservationResponseSchema],
  ["ChangeAvailability", ChangeAvailabilityRequestSchema, ChangeAvailabilityResponseSchema],
  ["ChangeConfiguration", ChangeConfigurationRequestSchema, ChangeConfigurationResponseSchema],
  ["ClearCache", ClearCacheRequestSchema, ClearCacheResponseSchema],
  ["ClearChargingProfile", ClearChargingProfileRequestSchema, ClearChargingProfileResponseSchema],
  ["DataTransfer", DataTransferRequestSchema, DataTransferResponseSchema],
  [
    "DiagnosticsStatusNotification",
    DiagnosticsStatusNotificationRequestSchema,
    DiagnosticsStatusNotificationResponseSchema,
  ],
  [
    "FirmwareStatusNotification",
    FirmwareStatusNotificationRequestSchema,
    FirmwareStatusNotificationResponseSchema,
  ],
  ["GetCompositeSchedule", GetCompositeScheduleRequestSchema, GetCompositeScheduleResponseSchema],
  ["GetConfiguration", GetConfigurationRequestSchema, GetConfigurationResponseSchema],
  ["GetDiagnostics", GetDiagnosticsRequestSchema, GetDiagnosticsResponseSchema],
  ["GetLocalListVersion", GetLocalListVersionRequestSchema, GetLocalListVersionResponseSchema],
  ["Heartbeat", HeartbeatRequestSchema, HeartbeatResponseSchema],
  ["MeterValues", MeterValuesRequestSchema, MeterValuesResponseSchema],
  [
    "RemoteStartTransaction",
    RemoteStartTransactionRequestSchema,
    RemoteStartTransactionResponseSchema,
  ],
  [
    "RemoteStopTransaction",
    RemoteStopTransactionRequestSchema,
    RemoteStopTransactionResponseSchema,
  ],
  ["ReserveNow", ReserveNowRequestSchema, ReserveNowResponseSchema],
  ["Reset", ResetRequestSchema, ResetResponseSchema],
  ["SendLocalList", SendLocalListRequestSchema, SendLocalListResponseSchema],
  ["SetChargingProfile", SetChargingProfileRequestSchema, SetChargingProfileResponseSchema],
  ["StartTransaction", StartTransactionRequestSchema, StartTransactionResponseSchema],
  ["StatusNotification", StatusNotificationRequestSchema, StatusNotificationResponseSchema],
  ["StopTransaction", StopTransactionRequestSchema, StopTransactionResponseSchema],
  ["TriggerMessage", TriggerMessageRequestSchema, TriggerMessageResponseSchema],
  ["UnlockConnector", UnlockConnectorRequestSchema, UnlockConnectorResponseSchema],
  ["UpdateFirmware", UpdateFirmwareRequestSchema, UpdateFirmwareResponseSchema],
] as const satisfies readonly SchemaCatalogPair[];
