import type { SchemaCatalogPair } from "../internal/catalogBuilder";

import {
  AuthorizeRequestSchema,
  AuthorizeResponseSchema,
  BootNotificationRequestSchema,
  BootNotificationResponseSchema,
  CancelReservationRequestSchema,
  CancelReservationResponseSchema,
  CertificateSignedRequestSchema,
  CertificateSignedResponseSchema,
  ChangeAvailabilityRequestSchema,
  ChangeAvailabilityResponseSchema,
  ClearCacheRequestSchema,
  ClearCacheResponseSchema,
  ClearChargingProfileRequestSchema,
  ClearChargingProfileResponseSchema,
  ClearDisplayMessageRequestSchema,
  ClearDisplayMessageResponseSchema,
  ClearedChargingLimitRequestSchema,
  ClearedChargingLimitResponseSchema,
  ClearVariableMonitoringRequestSchema,
  ClearVariableMonitoringResponseSchema,
  CostUpdatedRequestSchema,
  CostUpdatedResponseSchema,
  CustomerInformationRequestSchema,
  CustomerInformationResponseSchema,
  DataTransferRequestSchema,
  DataTransferResponseSchema,
  DeleteCertificateRequestSchema,
  DeleteCertificateResponseSchema,
  FirmwareStatusNotificationRequestSchema,
  FirmwareStatusNotificationResponseSchema,
  Get15118EVCertificateRequestSchema,
  Get15118EVCertificateResponseSchema,
  GetBaseReportRequestSchema,
  GetBaseReportResponseSchema,
  GetCertificateStatusRequestSchema,
  GetCertificateStatusResponseSchema,
  GetChargingProfilesRequestSchema,
  GetChargingProfilesResponseSchema,
  GetCompositeScheduleRequestSchema,
  GetCompositeScheduleResponseSchema,
  GetDisplayMessagesRequestSchema,
  GetDisplayMessagesResponseSchema,
  GetInstalledCertificateIdsRequestSchema,
  GetInstalledCertificateIdsResponseSchema,
  GetLocalListVersionRequestSchema,
  GetLocalListVersionResponseSchema,
  GetLogRequestSchema,
  GetLogResponseSchema,
  GetMonitoringReportRequestSchema,
  GetMonitoringReportResponseSchema,
  GetReportRequestSchema,
  GetReportResponseSchema,
  GetTransactionStatusRequestSchema,
  GetTransactionStatusResponseSchema,
  GetVariablesRequestSchema,
  GetVariablesResponseSchema,
  HeartbeatRequestSchema,
  HeartbeatResponseSchema,
  InstallCertificateRequestSchema,
  InstallCertificateResponseSchema,
  LogStatusNotificationRequestSchema,
  LogStatusNotificationResponseSchema,
  MeterValuesRequestSchema,
  MeterValuesResponseSchema,
  NotifyChargingLimitRequestSchema,
  NotifyChargingLimitResponseSchema,
  NotifyCustomerInformationRequestSchema,
  NotifyCustomerInformationResponseSchema,
  NotifyDisplayMessagesRequestSchema,
  NotifyDisplayMessagesResponseSchema,
  NotifyEVChargingNeedsRequestSchema,
  NotifyEVChargingNeedsResponseSchema,
  NotifyEVChargingScheduleRequestSchema,
  NotifyEVChargingScheduleResponseSchema,
  NotifyEventRequestSchema,
  NotifyEventResponseSchema,
  NotifyMonitoringReportRequestSchema,
  NotifyMonitoringReportResponseSchema,
  NotifyReportRequestSchema,
  NotifyReportResponseSchema,
  PublishFirmwareRequestSchema,
  PublishFirmwareResponseSchema,
  PublishFirmwareStatusNotificationRequestSchema,
  PublishFirmwareStatusNotificationResponseSchema,
  ReportChargingProfilesRequestSchema,
  ReportChargingProfilesResponseSchema,
  RequestStartTransactionRequestSchema,
  RequestStartTransactionResponseSchema,
  RequestStopTransactionRequestSchema,
  RequestStopTransactionResponseSchema,
  ReservationStatusUpdateRequestSchema,
  ReservationStatusUpdateResponseSchema,
  ReserveNowRequestSchema,
  ReserveNowResponseSchema,
  ResetRequestSchema,
  ResetResponseSchema,
  SecurityEventNotificationRequestSchema,
  SecurityEventNotificationResponseSchema,
  SendLocalListRequestSchema,
  SendLocalListResponseSchema,
  SetChargingProfileRequestSchema,
  SetChargingProfileResponseSchema,
  SetDisplayMessageRequestSchema,
  SetDisplayMessageResponseSchema,
  SetMonitoringBaseRequestSchema,
  SetMonitoringBaseResponseSchema,
  SetMonitoringLevelRequestSchema,
  SetMonitoringLevelResponseSchema,
  SetNetworkProfileRequestSchema,
  SetNetworkProfileResponseSchema,
  SetVariableMonitoringRequestSchema,
  SetVariableMonitoringResponseSchema,
  SetVariablesRequestSchema,
  SetVariablesResponseSchema,
  SignCertificateRequestSchema,
  SignCertificateResponseSchema,
  StatusNotificationRequestSchema,
  StatusNotificationResponseSchema,
  TransactionEventRequestSchema,
  TransactionEventResponseSchema,
  TriggerMessageRequestSchema,
  TriggerMessageResponseSchema,
  UnlockConnectorRequestSchema,
  UnlockConnectorResponseSchema,
  UnpublishFirmwareRequestSchema,
  UnpublishFirmwareResponseSchema,
  UpdateFirmwareRequestSchema,
  UpdateFirmwareResponseSchema,
} from "./schemas";

export const ocpp201SchemaPairs = [
  ["Authorize", AuthorizeRequestSchema, AuthorizeResponseSchema],
  ["BootNotification", BootNotificationRequestSchema, BootNotificationResponseSchema],
  ["CancelReservation", CancelReservationRequestSchema, CancelReservationResponseSchema],
  ["CertificateSigned", CertificateSignedRequestSchema, CertificateSignedResponseSchema],
  ["ChangeAvailability", ChangeAvailabilityRequestSchema, ChangeAvailabilityResponseSchema],
  ["ClearCache", ClearCacheRequestSchema, ClearCacheResponseSchema],
  ["ClearChargingProfile", ClearChargingProfileRequestSchema, ClearChargingProfileResponseSchema],
  ["ClearDisplayMessage", ClearDisplayMessageRequestSchema, ClearDisplayMessageResponseSchema],
  ["ClearedChargingLimit", ClearedChargingLimitRequestSchema, ClearedChargingLimitResponseSchema],
  [
    "ClearVariableMonitoring",
    ClearVariableMonitoringRequestSchema,
    ClearVariableMonitoringResponseSchema,
  ],
  ["CostUpdated", CostUpdatedRequestSchema, CostUpdatedResponseSchema],
  ["CustomerInformation", CustomerInformationRequestSchema, CustomerInformationResponseSchema],
  ["DataTransfer", DataTransferRequestSchema, DataTransferResponseSchema],
  ["DeleteCertificate", DeleteCertificateRequestSchema, DeleteCertificateResponseSchema],
  [
    "FirmwareStatusNotification",
    FirmwareStatusNotificationRequestSchema,
    FirmwareStatusNotificationResponseSchema,
  ],
  [
    "Get15118EVCertificate",
    Get15118EVCertificateRequestSchema,
    Get15118EVCertificateResponseSchema,
  ],
  ["GetBaseReport", GetBaseReportRequestSchema, GetBaseReportResponseSchema],
  ["GetCertificateStatus", GetCertificateStatusRequestSchema, GetCertificateStatusResponseSchema],
  ["GetChargingProfiles", GetChargingProfilesRequestSchema, GetChargingProfilesResponseSchema],
  ["GetCompositeSchedule", GetCompositeScheduleRequestSchema, GetCompositeScheduleResponseSchema],
  ["GetDisplayMessages", GetDisplayMessagesRequestSchema, GetDisplayMessagesResponseSchema],
  [
    "GetInstalledCertificateIds",
    GetInstalledCertificateIdsRequestSchema,
    GetInstalledCertificateIdsResponseSchema,
  ],
  ["GetLocalListVersion", GetLocalListVersionRequestSchema, GetLocalListVersionResponseSchema],
  ["GetLog", GetLogRequestSchema, GetLogResponseSchema],
  ["GetMonitoringReport", GetMonitoringReportRequestSchema, GetMonitoringReportResponseSchema],
  ["GetReport", GetReportRequestSchema, GetReportResponseSchema],
  ["GetTransactionStatus", GetTransactionStatusRequestSchema, GetTransactionStatusResponseSchema],
  ["GetVariables", GetVariablesRequestSchema, GetVariablesResponseSchema],
  ["Heartbeat", HeartbeatRequestSchema, HeartbeatResponseSchema],
  ["InstallCertificate", InstallCertificateRequestSchema, InstallCertificateResponseSchema],
  ["LogStatusNotification", LogStatusNotificationRequestSchema, LogStatusNotificationResponseSchema],
  ["MeterValues", MeterValuesRequestSchema, MeterValuesResponseSchema],
  ["NotifyChargingLimit", NotifyChargingLimitRequestSchema, NotifyChargingLimitResponseSchema],
  [
    "NotifyCustomerInformation",
    NotifyCustomerInformationRequestSchema,
    NotifyCustomerInformationResponseSchema,
  ],
  ["NotifyDisplayMessages", NotifyDisplayMessagesRequestSchema, NotifyDisplayMessagesResponseSchema],
  ["NotifyEVChargingNeeds", NotifyEVChargingNeedsRequestSchema, NotifyEVChargingNeedsResponseSchema],
  [
    "NotifyEVChargingSchedule",
    NotifyEVChargingScheduleRequestSchema,
    NotifyEVChargingScheduleResponseSchema,
  ],
  ["NotifyEvent", NotifyEventRequestSchema, NotifyEventResponseSchema],
  [
    "NotifyMonitoringReport",
    NotifyMonitoringReportRequestSchema,
    NotifyMonitoringReportResponseSchema,
  ],
  ["NotifyReport", NotifyReportRequestSchema, NotifyReportResponseSchema],
  ["PublishFirmware", PublishFirmwareRequestSchema, PublishFirmwareResponseSchema],
  [
    "PublishFirmwareStatusNotification",
    PublishFirmwareStatusNotificationRequestSchema,
    PublishFirmwareStatusNotificationResponseSchema,
  ],
  ["ReportChargingProfiles", ReportChargingProfilesRequestSchema, ReportChargingProfilesResponseSchema],
  [
    "RequestStartTransaction",
    RequestStartTransactionRequestSchema,
    RequestStartTransactionResponseSchema,
  ],
  [
    "RequestStopTransaction",
    RequestStopTransactionRequestSchema,
    RequestStopTransactionResponseSchema,
  ],
  [
    "ReservationStatusUpdate",
    ReservationStatusUpdateRequestSchema,
    ReservationStatusUpdateResponseSchema,
  ],
  ["ReserveNow", ReserveNowRequestSchema, ReserveNowResponseSchema],
  ["Reset", ResetRequestSchema, ResetResponseSchema],
  [
    "SecurityEventNotification",
    SecurityEventNotificationRequestSchema,
    SecurityEventNotificationResponseSchema,
  ],
  ["SendLocalList", SendLocalListRequestSchema, SendLocalListResponseSchema],
  ["SetChargingProfile", SetChargingProfileRequestSchema, SetChargingProfileResponseSchema],
  ["SetDisplayMessage", SetDisplayMessageRequestSchema, SetDisplayMessageResponseSchema],
  ["SetMonitoringBase", SetMonitoringBaseRequestSchema, SetMonitoringBaseResponseSchema],
  ["SetMonitoringLevel", SetMonitoringLevelRequestSchema, SetMonitoringLevelResponseSchema],
  ["SetNetworkProfile", SetNetworkProfileRequestSchema, SetNetworkProfileResponseSchema],
  [
    "SetVariableMonitoring",
    SetVariableMonitoringRequestSchema,
    SetVariableMonitoringResponseSchema,
  ],
  ["SetVariables", SetVariablesRequestSchema, SetVariablesResponseSchema],
  ["SignCertificate", SignCertificateRequestSchema, SignCertificateResponseSchema],
  ["StatusNotification", StatusNotificationRequestSchema, StatusNotificationResponseSchema],
  ["TransactionEvent", TransactionEventRequestSchema, TransactionEventResponseSchema],
  ["TriggerMessage", TriggerMessageRequestSchema, TriggerMessageResponseSchema],
  ["UnlockConnector", UnlockConnectorRequestSchema, UnlockConnectorResponseSchema],
  ["UnpublishFirmware", UnpublishFirmwareRequestSchema, UnpublishFirmwareResponseSchema],
  ["UpdateFirmware", UpdateFirmwareRequestSchema, UpdateFirmwareResponseSchema],
] as const satisfies readonly SchemaCatalogPair[];
